services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: ${FRONTEND_ENV:-prod}
    container_name: frontend
    image: zyplow-frontend
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./.env
    networks:
      - zyplow

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
      target: ${REDIS_ENV:-prod}
    image: zyplow-redis
    container_name: redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
      - "${REDIS_INSIGHT_PORT:-8001}:8001"
    env_file:
      - ./.env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - zyplow

networks:
  zyplow:
    name: zyplow
    driver: bridge
